// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("R.NET")>]
[<assembly: AssemblyCompanyAttribute("")>]
[<assembly: AssemblyProductAttribute("R.NET")>]
[<assembly: AssemblyDescriptionAttribute("Interoperability library to access the R statistical language runtime from .NET")>]
[<assembly: AssemblyVersionAttribute("1.9.1")>]
[<assembly: AssemblyFileVersionAttribute("1.9.1")>]
do ()

