// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("R.NET")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("R.NET")]
[assembly: AssemblyDescription("Interoperability library to access the R statistical language runtime from .NET")]
[assembly: AssemblyVersion("1.9.1")]
[assembly: AssemblyFileVersion("1.9.1")]
